//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Author: Henry
//------------------------------------------------------------------------------

namespace CulinaryPursuit
{
    public partial class AdminAnalytics
    {
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.Button btnApplyDateFilter;
        protected global::System.Web.UI.WebControls.Button btnResetFilter;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;
        protected global::System.Web.UI.WebControls.Label lblTotalCustomers;
        protected global::System.Web.UI.WebControls.Label lblNewCustomers;
        protected global::System.Web.UI.WebControls.Label lblActiveRestaurants;
        protected global::System.Web.UI.WebControls.Label lblTotalExpenses;
        protected global::System.Web.UI.WebControls.Label lblNetProfit;
        protected global::System.Web.UI.WebControls.Label lblProfitMargin;
        protected global::System.Web.UI.WebControls.Label lblAvgOrderValue;
        protected global::System.Web.UI.WebControls.Label lblDailyCustomers;
        protected global::System.Web.UI.WebControls.Repeater rptTopRestaurants;
        protected global::System.Web.UI.WebControls.Repeater rptCuisinePerformance;
        protected global::System.Web.UI.WebControls.Repeater rptSalesByCategory;
        protected global::System.Web.UI.WebControls.Literal litChartData;
    }
}
