//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Author: Henry
//------------------------------------------------------------------------------

namespace CulinaryPursuit
{
    public partial class AdminPlatformFees
    {
        /// <summary>
        /// lblPendingTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingTotal;

        /// <summary>
        /// lblPendingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingCount;

        /// <summary>
        /// lblOverdueTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOverdueTotal;

        /// <summary>
        /// lblOverdueCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOverdueCount;

        /// <summary>
        /// lblPaidTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPaidTotal;

        /// <summary>
        /// lblPaidCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPaidCount;

        /// <summary>
        /// lblTotalRevenue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// ddlRestaurant control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRestaurant;

        /// <summary>
        /// btnApplyFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilter;

        /// <summary>
        /// pnlFees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFees;

        /// <summary>
        /// rptFees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFees;

        /// <summary>
        /// pnlNoFees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoFees;
    }
}
