//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Author: Henry
//------------------------------------------------------------------------------

namespace CulinaryPursuit
{
    public partial class SellerAnalytics
    {
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.Button btnApplyFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Label lblRevenueGrowth;
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;
        protected global::System.Web.UI.WebControls.Label lblOrderGrowth;
        protected global::System.Web.UI.WebControls.Label lblUniqueCustomers;
        protected global::System.Web.UI.WebControls.Label lblRetentionRate;
        protected global::System.Web.UI.WebControls.Label lblAvgRating;
        protected global::System.Web.UI.WebControls.Label lblTotalReviews;
        protected global::System.Web.UI.WebControls.Label lblAvgOrderValue;
        protected global::System.Web.UI.WebControls.Label lblPlatformFees;
        protected global::System.Web.UI.WebControls.Label lblPendingFees;
        protected global::System.Web.UI.WebControls.Label lblNetEarnings;
        protected global::System.Web.UI.WebControls.Label lblDailyAverage;
        protected global::System.Web.UI.WebControls.Repeater rptTopItems;
        protected global::System.Web.UI.WebControls.Repeater rptCategories;
        protected global::System.Web.UI.WebControls.Repeater rptRecentOrders;
        protected global::System.Web.UI.WebControls.Literal litChartData;
    }
}
